export default function useSidebarStyles() {
  return {
    hamburger: {
      position: "absolute",
      top: 20,
      left: 20,
      fontSize: 40,
      color: "black",
      zIndex: 1300,
      display: { xs: "block", sm: "none" },
    },
    drawer: {
      "& .MuiDrawer-paper": {
        width: { xs: "70%", sm: 280 },
        background: "linear-gradient(130deg, rgba(120,197,244,1) 25%, rgba(5,66,103,1) 75%)",
        color: "white",
        borderTopRightRadius: "12px",
        borderBottomRightRadius: "12px",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        pt: 4,
      },
    },
    sidebar: {
      display: { xs: "none", sm: "flex" },
      flexDirection: "column",
      alignItems: "center",
      width: 280,
      height: "100vh",
      background: "linear-gradient(130deg, rgba(120,197,244,1) 25%, rgba(5,66,103,1) 75%)",
      borderTopRightRadius: 2,
      borderBottomRightRadius: 2,
      color: "white",
      pt: 4,
    },
    logo: {
      fontWeight: 800,
      mb: 3,
      textAlign: "center",
      color: "white",
      textShadow: "1px 1px 4px rgba(0,0,0,0.3)",
      fontSize: "1.8rem",
    },
    menuItem: {
      mx: 2,
      mb: 1,
      borderRadius: 2,
      bgcolor: "white",
      color: "black",
      "&:hover": {
        bgcolor: "#a1d3fd",
        transform: "scale(1.05)",
      },
      transition: "all 0.2s ease-in-out",
      boxShadow: "2px 2px 5px rgba(0,0,0,0.4)",
    },
    menuItemIcon: { color: "black", minWidth: 40 },
    logoutBox: { mt: "auto", mb: 2 },
    logoutButton: {
      color: "white",
      fontSize: 20,
      fontWeight: "bold",
      "&:hover": { color: "#a1d3fd" },
    },
    logoutButtonDesktop: {
      color: "white",
      fontSize: 20,
      fontWeight: "bold",
      mb: 2,
      "&:hover": { color: "#a1d3fd" },
    },
  };
}
